name: Daily build

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        run: bal test ./ballerina --test-report --code-coverage --coverage-format=xml
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.emailAddress }}
          PASSWORD: ${{ secrets.PASSWORD }}
          QUERY_NAME: ${{ secrets.QUERY_NAME }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
